site_name: Awesome Fetch
theme:
  name: terminal
  palette: dark
repo_name: beucismis/awesome-fetch
repo_url: https://github.com/beucismis/awesome-fetch
nav:
  - Home: index.md
  - License: LICENSE.md
  - Contributing: CONTRIBUTING.md
