site_name: Awesome Fetch
theme:
  name: terminal
  palette: dark
nav:
  - Home: index.md
  - Source Code: https://github.com/beucismis/awesome-fetch
  - License: LICENSE.md
  - Contributing: CONTRIBUTING.md
