import re
import sys
import json
from dataclasses import asdict, dataclass


@dataclass
class Tool:
    name: str
    url: str
    description: str
    language: str


README_FILE = sys.argv[1]
DATA_FILE = sys.argv[2]

# Regex pattern to match tools in the README file
# Example format: "- [Tool Name](Tool URL) - Description `Language`"
pattern = r"-\s\[(.*?)\]\((.*?)\)\s-\s(.*?)\s\`([^\`]+)\`"

with open(README_FILE, "r", encoding="utf-8") as readme_file:
    matches = re.findall(pattern, readme_file.read())

tools = [asdict(Tool(*match)) for match in matches]
data_content = {"comment": "Do not edit this file!", "total": len(tools), "tools": tools}

with open(DATA_FILE, "w+", encoding="utf-8") as file:
    json.dump(data_content, file, indent=2, ensure_ascii=False)
