import json
import re
import sys
from dataclasses import asdict, dataclass


@dataclass
class Tool:
    name: str
    source_url: str
    description: str
    programing_language: str


README_FILE_PATH = sys.argv[1]
DATA_FILE_PATH = sys.argv[2]

# Regex pattern to match tools in the README file
# Example format: "- [Name](Source URL) - Description `Programing Language`"
pattern = r"-\s\[(.*?)\]\((.*?)\)\s-\s(.*?)\s\`([^\`]+)\`"

with open(README_FILE_PATH, "r", encoding="utf-8") as readme_file:
    matches = re.findall(pattern, readme_file.read())

tools = [asdict(Tool(*match)) for match in matches]
data_content = {"comment": "Do not edit this file!", "total": len(tools), "tools": tools}

with open(DATA_FILE_PATH, "w+", encoding="utf-8") as file:
    json.dump(data_content, file, indent=2, ensure_ascii=False)
