name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup MkDocs
        run: |
          pip install mkdocs mkdocs-terminal
          mkdir docs
          cp README.md docs/index.md
          cp CONTRIBUTING.md docs/contributing.md
          mkdir -p docs/stylesheets
          cp site/extra.css docs/stylesheets/extra.css

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy -d site/ --force
